### ISSUE TITLE
Error message on backup

### ISSUE THREAD

**Issue by joaociocca** [Macro-Deck-App/Macro-Deck#343]
**Describe the bug**
I'm not sure? Log says the backup was successfully created, but then there's a "creation failed" error, makes no sense to me.
Also, backup does not show in list (I thought maybe list was just not refreshed, but leaving the backups section and coming back to it won't show it).

```
02:25:11 [Macro Deck] [Info] >> Sarting creation of backup: backup_23-01-18_02-25-11.zip
02:25:18 [Macro Deck] [Info] >> Backup successfully created: backup_23-01-18_02-25-11.zip
02:25:18 [Macro Deck] [Error] >> Backup creation failed: Não é possível chamar Invoke ou BeginInvoke em um controle antes da criação do identificador de janela.
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at SuchByte.MacroDeck.GUI.MainWindowContents.SettingsView.BackupManager_BackupSaved(Object sender, EventArgs e) in E:\Repos\Macro-Deck-WinForms\Macro-Deck\GUI\MainWindowViews\SettingsView.cs:line 382
   at SuchByte.MacroDeck.Backups.BackupManager.CreateBackup() in E:\Repos\Macro-Deck-WinForms\Macro-Deck\Backup\BackupManager.cs:line 263
```

Second attempt to reproduce:

```
02:28:52 [Macro Deck] [Info] >> Sarting creation of backup: backup_23-01-18_02-28-52.zip
02:28:53 [Macro Deck] [Info] >> Backup successfully created: backup_23-01-18_02-28-52.zip
02:28:53 [Macro Deck] [Error] >> Backup creation failed: Não é possível chamar Invoke ou BeginInvoke em um controle antes da criação do identificador de janela.
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at SuchByte.MacroDeck.GUI.MainWindowContents.SettingsView.BackupManager_BackupSaved(Object sender, EventArgs e) in E:\Repos\Macro-Deck-WinForms\Macro-Deck\GUI\MainWindowViews\SettingsView.cs:line 382
   at SuchByte.MacroDeck.Backups.BackupManager.CreateBackup() in E:\Repos\Macro-Deck-WinForms\Macro-Deck\Backup\BackupManager.cs:line 263
```

If you check backup names for date/time and the screenshot below, you'll see the 02:28 backup is missing.

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Backups'
3. Click on 'Create Backup'

**Expected behavior**
Backup created and no error messages.

**Screenshots**
![image](https://user-images.githubusercontent.com/6473725/213091735-ae960ffa-7c83-4567-a34a-b1e59155d9ed.png)

**Log file**
Already mentioned in description.

**Comment by manuelmayer-dev** [comment]
https://github.com/Macro-Deck-App/Macro-Deck/issues/293
