### ISSUE TITLE
client is not opening

### ISSUE THREAD

**Issue by davexxxxxx** [Macro-Deck-App/Macro-Deck#395]
The app is not launching. 
I've installed the HWiNFO64 Plugin, restarted system, after that it stopped working. Reinstall didn't help.
Here's the log:

[2023-04-20.log](https://github.com/Macro-Deck-App/Macro-Deck/files/11287695/2023-04-20.log)

**Comment by davexxxxxx** [comment]
Update: it's working after i deleted the HWiNFO64 Plugin file in C:\Users\David\AppData\Roaming\Macro Deck\plugins

**Comment by Falenone** [comment]
I have the same issue

12:02:55 [Macro Deck] [Info] >> PluginManager: Enabling plugins...
12:02:55 [Macro Deck] [Error] >> MacroDeck: CurrentDomainOnUnhandledException: System.NullReferenceException: Object reference not set to an instance of an object.
   at Ize.HWiNFO64_Plugin.HWiNFO64Plugin.Enable() in C:\Users\Manuel\Desktop\Macro Deck Compiler\Temp\Ize.HWiNFO64\Main.cs:line 36
   at SuchByte.MacroDeck.Plugins.PluginManager.EnablePlugins() in E:\Repos\Macro-Deck-WinForms\Macro-Deck\Plugins\PluginManager.cs:line 492
   at SuchByte.MacroDeck.MacroDeck.Start(Boolean show, Int32 port) in E:\Repos\Macro-Deck-WinForms\Macro-Deck\MacroDeck.cs:line 447
   at SuchByte.MacroDeck.MacroDeck.Main(String[] args) in E:\Repos\Macro-Deck-WinForms\Macro-Deck\MacroDeck.cs:line 415

Those file paths are not mine but I guess the one's who compiles hwinfo stuff?

**Comment by davexxxxxx** [comment]
I'd say so yea. But got no clue. Works just fine now after removing and reinstalling the plugin

**Comment by grabberverseknight** [comment]
So what i did with HWINFO64 plugin and the ize.speedtest
I just deleted them. 
Opened Macro Deck 2 Server and It just prompted for firewall bypass and works just fine!**


Just delete**

**Comment by grabberverseknight** [comment]
btw this was the log i was getting.

MacroDeck: CurrentDomainOnUnhandledException: System.NullReferenceException: Object reference not set to an instance of an object.
   at Ize.HWiNFO64_Plugin.HWiNFO64Plugin.Enable() in C:\Users\Manuel\Desktop\Macro Deck Compiler\Temp\Ize.HWiNFO64\Main.cs:line 36
   at SuchByte.MacroDeck.Plugins.PluginManager.EnablePlugins() in E:\Repos\Macro-Deck-WinForms\Macro-Deck\Plugins\PluginManager.cs:line 492
   at SuchByte.MacroDeck.MacroDeck.Start(Boolean show, Int32 port) in E:\Repos\Macro-Deck-WinForms\Macro-Deck\MacroDeck.cs:line 447
   at SuchByte.MacroDeck.MacroDeck.Main(String[] args) in E:\Repos\Macro-Deck-WinForms\Macro-Deck\MacroDeck.cs:line 415

**Comment by grabberverseknight** [comment]
> 

the funny thing was my user is not manuel so i guess it was misconfigured

who knows
