### ISSUE TITLE
The SSL connection could not be established, see inner exception.

### ISSUE THREAD

**Issue by hellishvictor** [Macro-Deck-App/Macro-Deck#506]
Hi, running the program everything goes fine, but on "Online" the extension store doesn't show plugins for add.
![sshot-1](https://github.com/Macro-Deck-App/Macro-Deck/assets/34694956/1bdbf05a-654b-4629-99af-2f1985fe6601)
![sshot-2](https://github.com/Macro-Deck-App/Macro-Deck/assets/34694956/4f77795c-d868-4b63-b748-8382cce18ce8)

Here is the log file:
````
[Macro Deck] [Error] >> Failed to automatically check for updates
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid because of errors in the certificate chain: UntrustedRoot
   at System.Net.Security.SslStream.CompleteHandshake(SslAuthenticationOptions sslAuthenticationOptions)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at System.Net.Http.Json.HttpClientJsonExtensions.<FromJsonAsyncCore>g__Core|12_0[TValue,TJsonOptions](HttpClient client, Task`1 responseTask, Boolean usingResponseHeadersRead, CancellationTokenSource linkedCTS, Func`4 deserializeMethod, TJsonOptions jsonOptions, CancellationToken cancellationToken)
   at SuchByte.MacroDeck.Services.UpdateService.CheckForUpdatesAsync(CancellationToken cancellationToken) in D:\a\Macro-Deck\Macro-Deck\MacroDeck\Services\UpdateService.cs:line 62
   at SuchByte.MacroDeck.Services.UpdateService.DoWork(CancellationToken cancellationToken) in D:\a\Macro-Deck\Macro-Deck\MacroDeck\Services\UpdateService.cs:line 126
[Macro Deck] [Error] >> Error while loading extensions from the extension store:
The SSL connection could not be established, see inner exception.
````

Cheers.

**Comment by manuelmayer-dev** [comment]
I cannot reproduce this issue. The certificate for the Extension Store is valid.

Are you able to access the following url in your browser?
https://extensionstore.api.macro-deck.app/rest/v2/extensions

**Comment by hellishvictor** [comment]
> Are you able to access the following url in your browser? https://extensionstore.api.macro-deck.app/rest/v2/extensions

On FireFox yes, its a json file, but on IE it showed_"There is a problem with this website's security certificate errors"_, which I solved installing [this](https://grillo.avnam.net/isrgrootx1.cer), and then double click on it –> _Install Certificate_ –> Next –> select the second option and go to examine –> select _“Entities Trusted Root Certification”_ –> Accept –> Next –> Finish.

Now it works! Thank you very much.

**Comment by hellishvictor** [comment]
> Are you able to access the following url in your browser? https://extensionstore.api.macro-deck.app/rest/v2/extensions

Solved installing [this](https://grillo.avnam.net/isrgrootx1.cer), and then double click on it –> _Install Certificate_ –> Next –> select the second option and go to examine –> select _“Entities Trusted Root Certification”_ –> Accept –> Next –> Finish.

Now it works! Thank you very much.

**Comment by hellishvictor** [comment]
> Are you able to access the following url in your browser? https://extensionstore.api.macro-deck.app/rest/v2/extensions

Solved installing [this](https://grillo.avnam.net/isrgrootx1.cer), and then double click on it –> _Install Certificate_ –> Next –> select the second option and go to examine –> select _“Entities Trusted Root Certification”_ –> Accept –> Next –> Finish.

Now it works! Thank you very much.
