### ISSUE TITLE
Macrodeck not opening after latest beta update

### ISSUE THREAD

**Issue by couchdevmonk** [Macro-Deck-App/Macro-Deck#538]
I updated the Macrodeck to the latest beta update via the client and now the app won't open. It briefly appears on the taskbar icon section and disappears as I hover over it.

**Log file - Can't attach file more than 25MBs so here is a snippet of where it all went wrong I'm guessing**

4:41:45 PM [Macro Deck] [Info] >> MacroDeckPipeServer: Initializing pipe server
4:41:46 PM [Macro Deck] [Info] >> AdbServerHelper: Starting ADB server using C:\Program Files\Macro Deck\Android Debug Bridge\adb.exe
4:41:46 PM [Macro Deck] [Info] >> AdbServerHelper: Unable to start ADB server
4:41:46 PM [Macro Deck] [Info] >> AdbServerHelper:  connected
4:41:46 PM [Macro Deck] [Info] >> Macro Deck startup finished (took 1142.698ms)
4:41:47 PM [Macro Deck] [Error] >> MacroDeck: CurrentDomainOnUnhandledException: AdvancedSharpAdbClient.Exceptions.InvalidKeyEventException: KeyEvent is invalid
   at AdvancedSharpAdbClient.DeviceCommands.DeviceClient.SendKeyEventAsync(String key, CancellationToken cancellationToken)
   at SuchByte.MacroDeck.Server.AdbServerHelper.StartMacroDeckClient(AdbClient adbDeviceClient, DeviceData device) in D:\a\Macro-Deck\Macro-Deck\MacroDeck\Server\AdbServerHelper.cs:line 165
   at SuchByte.MacroDeck.Server.AdbServerHelper.<>c.<<Monitor_DeviceConnected>b__9_0>d.MoveNext() in D:\a\Macro-Deck\Macro-Deck\MacroDeck\Server\AdbServerHelper.cs:line 110
--- End of stack trace from previous location ---
   at SuchByte.MacroDeck.Server.AdbServerHelper.RunForDevice(String serial, Func`3 action) in D:\a\Macro-Deck\Macro-Deck\MacroDeck\Server\AdbServerHelper.cs:line 60
   at SuchByte.MacroDeck.Server.AdbServerHelper.Monitor_DeviceConnected(Object sender, DeviceDataEventArgs e) in D:\a\Macro-Deck\Macro-Deck\MacroDeck\Server\AdbServerHelper.cs:line 108
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
4:42:05 PM [Macro Deck] [Info] >> Checking paths...
4:42:05 PM [Macro Deck] [Info] >> Checking paths done
4:42:05 PM [Macro Deck] [Info] >> Set log level to 0
4:42:05 PM [Macro Deck] [Info] >> Macro Deck 2.14.1
4:42:05 PM [Macro Deck] [Info] >> Path: C:\Program Files\Macro Deck\Macro Deck 2.exe
4:42:05 PM [Macro Deck] [Info] >> Start parameters: --port 0 --force-update False --test-channel False --export-default-strings False --portable False --show False --disable-file-logging False --log-level 0 --debug-console False --ignore-pid-check 0
4:42:05 PM [Macro Deck] [Info] >> Loading language files...
4:42:05 PM [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Bulgaria.json...
4:42:05 PM [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Chinese.json...
4:42:05 PM [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Dutch.json...
4:42:05 PM [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.English.json...
4:42:05 PM [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Filipino.json...
4:42:05 PM [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Finnish.json...
4:42:05 PM [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.French.json...
4:42:05 PM [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.German.json...
4:42:05 PM [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Hungarian.json...
4:42:05 PM [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Italian.json...
4:42:05 PM [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Japanese.json...
4:42:05 PM [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Korean.json...
4:42:05 PM [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Polish.json...
4:42:05 PM [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Portuguese.json...
4:42:05 PM [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Russian.json...
4:42:05 PM [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Spanish.json...
4:42:05 PM [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Turkish.json...
4:42:05 PM [Macro Deck] [Info] >> Set language to English
4:42:05 PM [Macro Deck] [Info] >> VariableManager: Initialize variables database...
4:42:05 PM [Macro Deck] [Info] >> VariableManager: 43 variables found
4:42:05 PM [Macro Deck] [Info] >> PluginManager: Loading plugins...
4:42:05 PM [Macro Deck] [Info] >> Loading plugin Speedtest
4:42:05 PM [Macro Deck] [Info] >> Loading plugin Discord Plugin
4:42:05 PM [Macro Deck] [Info] >> Loading plugin GPU_Z Plugin
4:42:05 PM [Macro Deck] [Info] >> Loading plugin Windows Utils
4:42:06 PM [Macro Deck] [Info] >> IconManager: Loading icon packs...
4:42:06 PM [Macro Deck] [Trace] >> Deleted variable gpu_z_BIOSUEFI
4:42:06 PM [Macro Deck] [Trace] >> Deleted variable gpu_z_BIOSUEFI
4:42:06 PM [Macro Deck] [Trace] >> Deleted variable gpu_z_BIOSVersion
4:42:06 PM [Macro Deck] [Trace] >> Deleted variable gpu_z_BIOSVersion
4:42:06 PM [Macro Deck] [Trace] >> Deleted variable gpu_z_Bus
4:42:06 PM [Macro Deck] [Trace] >> Deleted variable gpu_z_Bus

**Comment by couchdevmonk** [comment]
Latest log text after trying to open:

4:59:16 PM [Macro Deck] [Info] >> Loaded 4 profiles
4:59:16 PM [Macro Deck] [Info] >> Found network interfaces:
Ethernet - 192.168.0.101
Bluetooth Network Connection 2 - 169.254.163.42
Loopback Pseudo-Interface 1 - 127.0.0.1

4:59:16 PM [Macro Deck] [Info] >> MacroDeckPipeServer: Initializing pipe server
4:59:16 PM [Macro Deck] [Info] >> AdbServerHelper: Starting ADB server using C:\Program Files\Macro Deck\Android Debug Bridge\adb.exe
4:59:16 PM [Macro Deck] [Info] >> AdbServerHelper: Unable to start ADB server
4:59:16 PM [Macro Deck] [Info] >> AdbServerHelper:  connected
4:59:17 PM [Macro Deck] [Info] >> Macro Deck startup finished (took 1061.1343ms)
4:59:18 PM [Macro Deck] [Error] >> MacroDeck: CurrentDomainOnUnhandledException: AdvancedSharpAdbClient.Exceptions.InvalidKeyEventException: KeyEvent is invalid
   at AdvancedSharpAdbClient.DeviceCommands.DeviceClient.SendKeyEventAsync(String key, CancellationToken cancellationToken)
   at SuchByte.MacroDeck.Server.AdbServerHelper.StartMacroDeckClient(AdbClient adbDeviceClient, DeviceData device) in D:\a\Macro-Deck\Macro-Deck\MacroDeck\Server\AdbServerHelper.cs:line 165
   at SuchByte.MacroDeck.Server.AdbServerHelper.<>c.<<Monitor_DeviceConnected>b__9_0>d.MoveNext() in D:\a\Macro-Deck\Macro-Deck\MacroDeck\Server\AdbServerHelper.cs:line 110
--- End of stack trace from previous location ---
   at SuchByte.MacroDeck.Server.AdbServerHelper.RunForDevice(String serial, Func`3 action) in D:\a\Macro-Deck\Macro-Deck\MacroDeck\Server\AdbServerHelper.cs:line 60
   at SuchByte.MacroDeck.Server.AdbServerHelper.Monitor_DeviceConnected(Object sender, DeviceDataEventArgs e) in D:\a\Macro-Deck\Macro-Deck\MacroDeck\Server\AdbServerHelper.cs:line 108
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

**Comment by Veklich28** [comment]
Всё поломали своими обновлениями... печально...

**Comment by couchdevmonk** [comment]
Update: closing the adb process in the task manager and restarting the server app worked.
Also disabled the adb setting in the "Connections" tab for the future.

**Comment by Veklich28** [comment]
> Всё поломали своими обновлениями... печально...
Удалил обновленное ПО и установил то что было изначально: сервер macro-deck-2.12.0.221941808 и клиент  Macro Deck - PC remote control pad-v1.3.1.apk. Всё заработало.
