### ISSUE TITLE
icon do not appear

### ISSUE THREAD

**Issue by tstex7pq** [Macro-Deck-App/Macro-Deck#547]
icon do not appear
update from v2.12 to 2.14

**Log file**
16:50:31 [Macro Deck] [Error] >> MacroDeck: ApplicationThreadException: Invoke or BeginInvoke cannot be called on a control until the window handle has been created.
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at System.Windows.Forms.Control.Invoke(Action method)
   at SuchByte.MacroDeck.GUI.CustomControls.ExtensionsView.ExtensionStoreView.SetLoading(Boolean state) in D:\a\Macro-Deck\Macro-Deck\MacroDeck\GUI\CustomControls\ExtensionsView\ExtensionStoreView.cs:line 121
   at SuchByte.MacroDeck.GUI.CustomControls.ExtensionsView.ExtensionStoreView.LoadExtensions() in D:\a\Macro-Deck\Macro-Deck\MacroDeck\GUI\CustomControls\ExtensionsView\ExtensionStoreView.cs:line 64
   at SuchByte.MacroDeck.GUI.CustomControls.ExtensionsView.ExtensionStoreView.CheckPlugins_CheckedChanged(Object sender, EventArgs e) in D:\a\Macro-Deck\Macro-Deck\MacroDeck\GUI\CustomControls\ExtensionsView\ExtensionStoreView.cs:line 134
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at InvokeStub_SendOrPostCallback.Invoke(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)

**Comment by manuelmayer-dev** [comment]
This issue is related to Macro Deck 2, which is no longer actively developed.

Macro Deck 3 is now the active version. If this issue is still relevant in Macro Deck 3, please create a new issue in the Macro Deck 3 repository so it can be tracked separately.
