### ISSUE TITLE
Template Editor Doesn't Work With Non-German Keyboard

### ISSUE THREAD

**Issue by paulthepen** [Macro-Deck-App/Macro-Deck#559]
**Describe the bug**
The Template Editor window doesn't open when using an English keyboard

**To Reproduce**
1. Open Macro Edit configuration
2. Right click a button and click 'Edit'
3. Click the pop out button next to the label
4. Nothing happens and the following error appears in the log: MacroDeck: ApplicationThreadException: Requested value 'Bild auf' was not found.

**Additional context**
I'm not a C# programmer, but from what I can tell, the issue is in TemplateEditor.resx line 121 where the hotkeys are all declared in German

**Log file**
00:03:44 [Macro Deck] [Error] >> MacroDeck: ApplicationThreadException: Requested value 'Bild auf' was not found.
   at System.Enum.TryParseByName[TStorage](RuntimeType enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, TStorage& result)
   at System.Enum.TryParseByValueOrName[TUnderlying,TStorage](RuntimeType enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, TUnderlying& result)
   at System.Enum.TryParse(Type enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, Object& result)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at System.Windows.Forms.KeysConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at FastColoredTextBoxNS.Input.HotkeysMapping.Parse(String s)
   at FastColoredTextBoxNS.FastColoredTextBox.set_Hotkeys(String value)
   at SuchByte.MacroDeck.GUI.Dialogs.TemplateEditor.InitializeComponent() in D:\a\Macro-Deck\Macro-Deck\MacroDeck\GUI\Dialogs\TemplateEditor.Designer.cs:line 83
   at SuchByte.MacroDeck.GUI.Dialogs.TemplateEditor..ctor(String template) in D:\a\Macro-Deck\Macro-Deck\MacroDeck\GUI\Dialogs\TemplateEditor.cs:line 44
   at SuchByte.MacroDeck.GUI.ButtonEditor.BtnOpenTemplateEditor_Click(Object sender, EventArgs e) in D:\a\Macro-Deck\Macro-Deck\MacroDeck\GUI\Dialogs\ButtonEditor.cs:line 513
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)

**Comment by manuelmayer-dev** [comment]
This issue is related to Macro Deck 2, which is no longer actively developed.

Macro Deck 3 is now the active version. If this issue is still relevant in Macro Deck 3, please create a new issue in the Macro Deck 3 repository so it can be tracked separately.
