### ISSUE TITLE
Cant connect to OBS websocket after Updating

### ISSUE THREAD

**Issue by needhelptoconnect** [Macro-Deck-App/Macro-Deck#569]
UPDATED app and it is unable to connect to the OBS websocket

I click connect on the obs symbol and it wont turn green

Worked perfectly for a year, updated it and it wont connect to obs anymore. 

1:02:14 PM [Macro Deck] [Error] >> MacroDeck: ApplicationThreadException: database disk image is malformed
   at SQLite.PreparedSqlLiteInsertCommand.ExecuteNonQuery(Object[] source)
   at SQLite.SQLiteConnection.Insert(Object obj, String extra, Type objType)
   at SQLite.SQLiteConnection.Insert(Object obj)
   at SuchByte.MacroDeck.Variables.VariableManager.SetValue(String name, Object value, VariableType type, String creator)
   at SuchByte.MacroDeck.Variables.VariableManager.SetValue(String name, Object value, VariableType type, String[] suggestions, String creator)
   at SuchByte.MacroDeck.Variables.VariableManager.SetValue(String name, Object value, VariableType type, MacroDeckPlugin plugin, String[] suggestions)
   at SuchByte.OBSWebSocketPlugin.Controllers.Connection.SetVariable(String name, String value, String[] suggestions)
   at SuchByte.OBSWebSocketPlugin.Controllers.Connection.SetVariable(String name, String value)
   at SuchByte.OBSWebSocketPlugin.Main.ResetVariables(Connection connection)
   at SuchByte.OBSWebSocketPlugin.Main.StoreConnectConnectionAsync(Connection connection)
   at SuchByte.OBSWebSocketPlugin.GUI.Controls.ConnectionToggler.OnConnectButtonClicked(Object sender, EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)

**Comment by manuelmayer-dev** [comment]
This issue is related to Macro Deck 2, which is no longer actively developed.

Macro Deck 3 is now the active version. If this issue is still relevant in Macro Deck 3, please create a new issue in the Macro Deck 3 repository so it can be tracked separately.
